baseURL = "https://radar.powertrader.es/"  # Importante la barra al final y el https
languageCode = "es-es"
title = "PowerRadar Semanal"
theme = "PaperMod"

[params]
    env = "production"
    title = "PowerRadar"
    description = "Análisis semanal de tendencias energéticas"
    author = "PowerTrader"
    defaultTheme = "dark" # Forzamos el modo oscuro

    [params.assets]
        disableHLJS = true
        disableFingerprinting = true # ESTO ARREGLA EL CSS ROTO A MENUDO

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

# Añadir al final del archivo hugo.toml
[[menu.main]]
    identifier = "universe"
    name = "⮌ Volver a PowerTrader"
    url = "https://powertrader.es"
    weight = 10

[sitemap]
  changefreq = "weekly"
  priority = 0.8
  filename = "sitemap.xml"
